### ISSUE TITLE
AttributeError: 'RNN' object has no attribute 'fit'

### ISSUE THREAD

**Issue by mayank-umn** [CallMeTwitch/Neural-Network-Zoo#1]
Getting the following error below:
Please suggest what to do?
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_11272\2182112111.py in <module>
      3 
      4 ##### Training #####
----> 5 rnn.fit(train_X, train_y)
      6 
      7 ##### Testing #####

AttributeError: 'RNN' object has no attribute 'fit'

**Comment by CallMeTwitch** [comment]
Hello mayank-umn.

It looks like you're calling ".fit()" on the RNN class. ".fit()" is a function that's used in Tensorflow to train a neural network. The RNN class I've implemented uses NumPy instead of Tensorflow, so you can use ".train()" instead. The files in this repo should work out of the box, so as long as you don't change them there shouldn't be any issues.

That is, replace "rnn.fit(train_X, train_y)" with "rnn.train(train_X, train_y)".

Hope this helps.
